# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoRestClient',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('config', jsonfield.fields.JSONField(default={})),
            ],
            options={
                'db_table': 'django_rest_client',
            },
        ),
    ]
